### ISSUE TITLE
BUG: ADBC Postgres writer results in incorrect table nane when specifying a schema

### ISSUE THREAD

**Issue by jorisvandenbossche** [jorisvandenbossche/euroscipy-2023-pandas-sprint#10]
See https://github.com/pandas-dev/pandas/issues/57539

**Comment by shabab477** [comment]
take

**Comment by jorisvandenbossche** [comment]
Some context: the `adbc_ingest` function that pandas is using has a `db_schema_name` keyword (https://arrow.apache.org/adbc/current/python/api/adbc_driver_manager.html#adbc_driver_manager.dbapi.Cursor.adbc_ingest). 
That should be used instead of creating the table name as "schema.name" pattern that is currently done at https://github.com/pandas-dev/pandas/blob/e51039afe3cbdedbf5ffd5cefb5dea98c2050b88/pandas/io/sql.py#L2356-L2357
