### ISSUE TITLE
DOC: fix the dev version label in the version dropdown

### ISSUE THREAD

**Issue by jorisvandenbossche** [jorisvandenbossche/euroscipy-2023-pandas-sprint#9]
Until recently, the label in the version dropwdown for the development docs was a simple "dev" (the label shown when being on the dev docs, not the label in the expanded dropdown list):

![image](https://github.com/jorisvandenbossche/pydata-amsterdam-pandas-sprint/assets/1020496/72dd8ccc-3085-44a1-b3e8-a8281be5f9d7)

But recently this changed to contain the full pandas version:

![image](https://github.com/jorisvandenbossche/pydata-amsterdam-pandas-sprint/assets/1020496/c8233e8d-e0e1-40ff-9aa3-9dd6ddfa1e7a)

Maybe it's nice that it includes the release number, but adding the whole commit hash is certainly unnecessary noise IMO (eg maybe "2.2.0.dev" would be sufficient if we want a number included?)

**Comment by hkhojasteh** [comment]
I can try to fix this one :)
